// Public imports
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

//* Font config
const inter = Inter({ subsets: ['latin'] });

//* Import components
import Providers from './providers';

//* Metadata tags
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
